// Package resourcepolicy is the foundational slice of the model-first resource
// generator (ADR-016, issue #352). It defines the `gombit` field-policy tag and
// resolves, per model field, the API behavior the generator derives DTOs,
// mappers, and CRUD plumbing from.
//
// Ownership of facts is deliberately split (ADR-016): the GORM schema owns
// persistence facts (DB-backed / primary key / auto-increment / DB default /
// nullability / auto timestamp / soft-delete / column name) and policy MUST NOT
// restate them. This resolver carries those facts losslessly — it never collapses
// them — because create-source correctness depends on the exact combination (a
// manual string key is not auto-generated; a NOT NULL column with no default must
// be supplied on create). The `gombit` tag owns only API behavior:
//
//	read     the field appears in the response DTO
//	write    the field is settable via the create request DTO (create source = request)
//	server   the field is set server-side (a hook), not from the request (create source = server)
//	-        the field is hidden from the API (no request, no response)
//
// `-` may combine with `server` (hidden from the API but set by a hook); it may
// not combine with `read`/`write`, and `write`+`server` conflict. A field with no
// `gombit` tag defaults by kind: a regular content column and a manual primary
// key are read+write from the request; an auto-increment key and auto timestamps
// are read-only; soft-delete is hidden. Resolve rejects a required column (NOT
// NULL / primary key, no DB default, not auto-generated) that ends up with no
// create source — the silent zero-fill #352 exists to eliminate.
//
// Persistence facts are supplied by the caller (slice 2 reads them from the
// model); this slice is pure and side-effect free.
package resourcepolicy

import (
	"fmt"
	"sort"
	"strings"
)

// FieldFacts are the persistence facts about a model field, owned by the GORM
// schema. Policy never restates these; it only layers API behavior on top. The
// facts are kept independent (not collapsed) because create-source correctness
// depends on their exact combination.
type FieldFacts struct {
	GoName        string // Go field name, e.g. "Title"
	Column        string // DB column name, e.g. "title"; empty for a relationship/association field
	DBBacked      bool   // maps to a database column (false for has_many/many2many/belongs-to object fields)
	PrimaryKey    bool
	AutoIncrement bool // database-generated key (serial/identity)
	AutoTime      bool // auto create/update timestamp (autoCreateTime/autoUpdateTime)
	SoftDelete    bool // gorm.DeletedAt
	NotNull       bool // NOT NULL constraint
	HasDefault    bool // has a database default value

	// Creatable / Readable mirror GORM's per-field permissions (schema.Field
	// Creatable/Readable, driven by the `->`/`<-` permission tags), independent of
	// whether the field has a column. GORM OMITS non-creatable fields from INSERT
	// and skips non-readable fields on SELECT, so policy must honor them or the API
	// promises an operation persistence will not perform. Normal columns are both
	// true; a `gorm:"->"` read-only/computed column is Creatable=false, and a
	// `gorm:"->:false;<-:create"` column is Readable=false.
	Creatable bool
	Readable  bool
}

// autoGenerated reports whether the database or GORM fills the column itself, so
// it is never settable through the create request and needs no create source. A
// primary key is auto-generated only when it is an auto-increment/identity key —
// a manual string/UUID key is not.
func (f FieldFacts) autoGenerated() bool {
	return f.AutoIncrement || f.AutoTime || f.SoftDelete
}

// requiresCreateValue reports whether the column must be given a value on create
// or it will be silently zero-filled: NOT NULL (a primary key is implicitly so),
// no database default, not auto-generated, and one GORM actually writes on INSERT
// (Creatable). A non-creatable column (`gorm:"->"`) is filled by the DB/GORM, not
// by us, so we make no create-source demand on it.
func (f FieldFacts) requiresCreateValue() bool {
	if !f.DBBacked || !f.Creatable {
		return false
	}
	return (f.NotNull || f.PrimaryKey) && !f.HasDefault && !f.autoGenerated()
}

// CreateSource is where a persisted field's create value comes from.
type CreateSource int

const (
	// CreateSourceNone is for fields the create path does not set (auto-generated,
	// or a nullable/defaulted column left unset, or not DB-backed).
	CreateSourceNone CreateSource = iota
	// CreateSourceRequest: the value comes from the create request body.
	CreateSourceRequest
	// CreateSourceServer: the value is set server-side (a BeforeCreate hook).
	CreateSourceServer
)

func (s CreateSource) String() string {
	switch s {
	case CreateSourceRequest:
		return "request"
	case CreateSourceServer:
		return "server"
	default:
		return "none"
	}
}

// Resolved is a field's resolved API behavior: its persistence facts plus where
// it appears in the API and where its create value comes from.
type Resolved struct {
	FieldFacts
	InRequest    bool         // settable via the create request DTO
	InResponse   bool         // surfaced in the response DTO
	CreateSource CreateSource // where a persisted create value comes from
}

// Field pairs a field's persistence facts with its raw `gombit` tag. It keeps the
// association 1:1: GORM can flatten two embedded fields to the same GoName with
// different columns and tags, so policy is never keyed by name.
type Field struct {
	FieldFacts
	Tag string
}

// policyTag is the parsed intent of a `gombit:"..."` tag.
type policyTag struct {
	present bool
	read    bool
	write   bool
	server  bool
	hidden  bool
}

// parsePolicyTag parses the comma-separated `gombit` tag value. An empty tag
// (field carried no `gombit:"..."`) yields present=false, so kind defaults apply.
func parsePolicyTag(tag string) (policyTag, error) {
	p := policyTag{}
	tag = strings.TrimSpace(tag)
	if tag == "" {
		return p, nil
	}
	p.present = true
	for _, tok := range strings.Split(tag, ",") {
		switch strings.TrimSpace(tok) {
		case "read":
			p.read = true
		case "write":
			p.write = true
		case "server":
			p.server = true
		case "-":
			p.hidden = true
		case "":
			// tolerate a stray empty token from a trailing comma
		default:
			return p, fmt.Errorf("resourcepolicy: unknown gombit policy token %q (want read, write, server, or -)", strings.TrimSpace(tok))
		}
	}
	if p.hidden && (p.read || p.write) {
		return p, fmt.Errorf("resourcepolicy: gombit:\"-\" (hidden) cannot be combined with read/write (it may combine with server)")
	}
	if p.write && p.server {
		return p, fmt.Errorf("resourcepolicy: gombit tag has both write and server; a field is set from the request OR server-side, not both")
	}
	return p, nil
}

// Resolve combines a field's persistence facts with its `gombit` tag into its API
// behavior. It errors on a contradictory tag (writing/server-setting an
// auto-generated column, write+server, tagging a relationship) and on a required
// column that ends up with no create source (which would be silently zero-filled).
func Resolve(facts FieldFacts, gombitTag string) (Resolved, error) {
	tag, err := parsePolicyTag(gombitTag)
	if err != nil {
		return Resolved{}, err
	}
	r := Resolved{FieldFacts: facts, CreateSource: CreateSourceNone}

	// A relationship/association field is not a scalar wire column; it is not part
	// of the derived request/response DTOs (belongs-to exposes its FK column, which
	// is itself DB-backed and handled as a normal field).
	if !facts.DBBacked {
		if tag.present {
			return Resolved{}, fmt.Errorf("resourcepolicy: field %q is not a database column (relationship); it cannot carry a gombit API policy", facts.GoName)
		}
		return r, nil
	}

	// Auto-generated columns (auto-increment key, auto timestamps, soft-delete) are
	// filled by the DB/GORM: never writable or server-set, never a create source.
	if facts.autoGenerated() {
		if tag.write || tag.server {
			return Resolved{}, fmt.Errorf("resourcepolicy: column %q is auto-generated (auto-increment / timestamp / soft-delete) and cannot be written or server-set", facts.Column)
		}
		if tag.read && !facts.Readable {
			return Resolved{}, fmt.Errorf("resourcepolicy: column %q is not readable (GORM `->` permission) and cannot be in the response", facts.Column)
		}
		if tag.present {
			r.InResponse = tag.read
		} else {
			r.InResponse = facts.Readable && !facts.SoftDelete // PK and timestamps read; soft-delete hidden
		}
		return r, nil
	}

	// A regular content column or a manual (non-auto) primary key. It may be read,
	// written from the request, or set server-side — but only where GORM actually
	// performs the operation: a non-creatable field (`gorm:"->"` / `<-:update`) is
	// omitted from INSERT, and a non-readable field is skipped on SELECT, so a tag
	// asking for those fails closed rather than promising a no-op.
	if tag.write && !facts.Creatable {
		return Resolved{}, fmt.Errorf("resourcepolicy: column %q is not creatable (GORM omits it from INSERT) and cannot be written", facts.Column)
	}
	if tag.server && !facts.Creatable {
		return Resolved{}, fmt.Errorf("resourcepolicy: column %q is not creatable (GORM omits it from INSERT); a server-set value would be discarded", facts.Column)
	}
	if tag.read && !facts.Readable {
		return Resolved{}, fmt.Errorf("resourcepolicy: column %q is not readable (GORM skips it on SELECT) and cannot be in the response", facts.Column)
	}

	if tag.present {
		r.InResponse = tag.read
		r.InRequest = tag.write
		switch {
		case tag.write:
			r.CreateSource = CreateSourceRequest
		case tag.server:
			r.CreateSource = CreateSourceServer
		}
	} else {
		// Defaults respect capabilities: readable → response, creatable → request.
		r.InResponse = facts.Readable
		r.InRequest = facts.Creatable
		if facts.Creatable {
			r.CreateSource = CreateSourceRequest
		}
	}

	// A required column with no create source would be silently zero-filled (#352).
	if facts.requiresCreateValue() && r.CreateSource == CreateSourceNone {
		return Resolved{}, fmt.Errorf("resourcepolicy: required column %q has no create source: add write (from the request), server (a hook), a database default, or make it nullable", facts.Column)
	}
	return r, nil
}

// ResolveAll resolves every field, in input order, preserving each field's own
// facts+tag pairing (never keyed by the possibly-ambiguous Go name). It fails on
// the first contradictory field so the generator never emits from a bad policy.
func ResolveAll(fields []Field) ([]Resolved, error) {
	out := make([]Resolved, 0, len(fields))
	for _, f := range fields {
		r, err := Resolve(f.FieldFacts, f.Tag)
		if err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, nil
}

// RequestColumns returns the DB column names settable via the create request,
// sorted — the write surface the generated request DTO must expose.
func RequestColumns(resolved []Resolved) []string {
	return columnsWhere(resolved, func(r Resolved) bool { return r.InRequest })
}

// ResponseColumns returns the DB column names surfaced in responses, sorted.
func ResponseColumns(resolved []Resolved) []string {
	return columnsWhere(resolved, func(r Resolved) bool { return r.InResponse })
}

// ServerColumns returns the DB column names whose create value is set server-side
// (a hook), sorted — the create-time non-request source.
func ServerColumns(resolved []Resolved) []string {
	return columnsWhere(resolved, func(r Resolved) bool { return r.CreateSource == CreateSourceServer })
}

func columnsWhere(resolved []Resolved, keep func(Resolved) bool) []string {
	var out []string
	for _, r := range resolved {
		if r.Column != "" && keep(r) {
			out = append(out, r.Column)
		}
	}
	sort.Strings(out)
	return out
}
