// Code generated by gombit make resource. DO NOT EDIT.
package document

import (
	filefield "github.com/gombit-dev/gombit/storage/filefield"
	upload "github.com/gombit-dev/gombit/storage/upload"
	types "github.com/gombit-dev/gombit/types"
	time "time"
)

// documentData is the response body for a Document.
type documentData struct {
	ID         uint                `json:"id" doc:"ID"`
	CreatedAt  time.Time           `json:"created_at" doc:"CreatedAt"`
	UpdatedAt  time.Time           `json:"updated_at" doc:"UpdatedAt"`
	Title      string              `json:"title" doc:"Title"`
	Attachment *filefield.FileInfo `json:"attachment" doc:"Attachment (a file: key, filename, size, type, and a download URL)"`
	Cover      *filefield.FileInfo `json:"cover" doc:"Cover (a file: key, filename, size, type, and a download URL)"`
}

// documentCreateBody is the request body for creating a Document.
type documentCreateBody struct {
	Title      string       `json:"title" minLength:"1" maxLength:"255" doc:"Title"`
	Attachment types.File   `json:"attachment" minLength:"1" maxLength:"512" doc:"Attachment"`
	Cover      *types.Image `json:"cover" minLength:"1" nullable:"true" maxLength:"512" doc:"Cover"`
}

// toDocumentData projects a Document into its response DTO.
func toDocumentData(row Document) documentData {
	return documentData{
		ID:        row.ID,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
		Title:     row.Title,
	}
}

// documentAttachmentPolicy is the Attachment field's upload policy (its storage tag).
var documentAttachmentPolicy = upload.Policy{
	Prefix:   "document/attachment/",
	MaxBytes: 10485760,
	Types:    []string{"application/pdf", "image/png", "image/jpeg", "text/plain"},
}

// documentCoverPolicy is the Cover field's upload policy (its storage tag).
var documentCoverPolicy = upload.Policy{
	Prefix:   "document/cover/",
	MaxBytes: 2097152,
	Types:    []string{"image/png", "image/jpeg", "image/gif", "image/webp"},
}

// documentFromCreateBody builds a new Document from a create request.
func documentFromCreateBody(body documentCreateBody) Document {
	var row Document
	row.Title = body.Title
	row.Attachment = body.Attachment
	row.Cover = body.Cover
	return row
}
