// Code generated by gombit make resource. DO NOT EDIT.
package document

import (
	"context"
	"net/http"
	"strconv"

	"github.com/danielgtaylor/huma/v2"
	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/database"
	"github.com/gombit-dev/gombit/framework"
	"github.com/gombit-dev/gombit/storage"
	"github.com/gombit-dev/gombit/storage/filefield"
	"gorm.io/gorm"
)

// DocumentHooks are the customization points for the generated Document handler.
// The generated handler owns the invariant CRUD sequence and calls these; set
// server-managed columns (tenant, owner, …) in BeforeCreate rather than editing
// generated plumbing.
type DocumentHooks interface {
	BeforeCreate(ctx context.Context, row *Document, body documentCreateBody) error
}

// Handler serves Document HTTP operations over GORM. Register wires DB and Hooks.
type Handler struct {
	DB    *gorm.DB
	Hooks DocumentHooks
	// Store holds the files of the resource's file fields.
	Store storage.Storage
}

type listDocumentsOutput struct {
	Body contract.DataMeta[[]documentData, contract.PageMeta]
}

type listDocumentsInput struct {
	Page    int `query:"page" doc:"1-based page"`
	PerPage int `query:"per_page" doc:"Page size"`
}

type getDocumentInput struct {
	ID string `path:"id" doc:"Document identifier"`
}

type getDocumentOutput struct {
	Body contract.Data[documentData]
}

type createDocumentInput struct {
	Body documentCreateBody
}

type createDocumentOutput struct {
	Body contract.Data[documentData]
}

func (h *Handler) list(ctx context.Context, input *listDocumentsInput) (*listDocumentsOutput, error) {
	page, perPage := contract.ClampPage(input.Page, input.PerPage)
	q := h.DB.WithContext(ctx).Model(&Document{})
	var total int64
	if err := q.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list documents"))
	}
	var rows []Document
	if err := q.Order("id").Offset(contract.PageOffset(page, perPage)).Limit(perPage).Find(&rows).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list documents"))
	}
	items := make([]documentData, 0, len(rows))
	for _, row := range rows {
		item := toDocumentData(row)
		if err := h.resolveFiles(ctx, row, &item); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return &listDocumentsOutput{
		Body: contract.DataMeta[[]documentData, contract.PageMeta]{
			Data: items,
			Meta: &contract.PageMeta{Page: page, PerPage: perPage, Total: total},
		},
	}, nil
}

func (h *Handler) get(ctx context.Context, input *getDocumentInput) (*getDocumentOutput, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, contract.WithContext(ctx, contract.NotFound("document not found"))
	}
	var row Document
	if err := h.DB.WithContext(ctx).First(&row, uint(id)).Error; err != nil {
		return nil, database.MapLoadError(ctx, err, "document not found", "load document")
	}
	item := toDocumentData(row)
	if err := h.resolveFiles(ctx, row, &item); err != nil {
		return nil, err
	}
	return &getDocumentOutput{Body: contract.Data[documentData]{Data: item}}, nil
}

func (h *Handler) create(ctx context.Context, input *createDocumentInput) (*createDocumentOutput, error) {
	if h.Hooks == nil {
		return nil, contract.WithContext(ctx, contract.Internal("create document: Handler.Hooks is not set"))
	}
	row := documentFromCreateBody(input.Body)
	if err := h.Hooks.BeforeCreate(ctx, &row, input.Body); err != nil {
		return nil, err
	}
	if err := h.acceptFiles(ctx, row); err != nil {
		return nil, err
	}
	if err := h.DB.WithContext(ctx).Create(&row).Error; err != nil {
		return nil, database.MapPersistError(ctx, err, "resource already exists", "create document")
	}
	item := toDocumentData(row)
	if err := h.resolveFiles(ctx, row, &item); err != nil {
		return nil, err
	}
	return &createDocumentOutput{Body: contract.Data[documentData]{Data: item}}, nil
}

// resolveFiles describes the row's files in its response (key, filename,
// size, type, download URL).
func (h *Handler) resolveFiles(ctx context.Context, row Document, item *documentData) error {
	var err error
	if item.Attachment, err = filefield.Resolve(ctx, h.Store, string(row.Attachment)); err != nil {
		return filefield.MapError(ctx, err)
	}
	if item.Cover, err = filefield.Resolve(ctx, h.Store, filefield.KeyOf(row.Cover)); err != nil {
		return filefield.MapError(ctx, err)
	}
	return nil
}

// acceptFiles checks the files a new row names: each an upload that passes
// its field's policy (by its bytes) and that no other row holds.
func (h *Handler) acceptFiles(ctx context.Context, row Document) error {
	if err := filefield.Accept(ctx, h.DB, h.Store, &Document{}, "attachment", string(row.Attachment), documentAttachmentPolicy); err != nil {
		return filefield.MapError(ctx, err)
	}
	if err := filefield.Accept(ctx, h.DB, h.Store, &Document{}, "cover", filefield.KeyOf(row.Cover), documentCoverPolicy); err != nil {
		return filefield.MapError(ctx, err)
	}
	return nil
}

type uploadDocumentFileOutput struct {
	Body contract.Data[filefield.UploadGrant]
}

type uploadDocumentAttachmentInput struct {
	Body filefield.UploadGrantRequest
}

// uploadAttachment grants the client one direct upload for the attachment field:
// it sends the returned request, then creates the document with the key.
// Hooks with a BeforeUpload(ctx, field) method decide who may upload.
func (h *Handler) uploadAttachment(ctx context.Context, input *uploadDocumentAttachmentInput) (*uploadDocumentFileOutput, error) {
	if hk, ok := h.Hooks.(interface {
		BeforeUpload(ctx context.Context, field string) error
	}); ok {
		if err := hk.BeforeUpload(ctx, "attachment"); err != nil {
			return nil, err
		}
	}
	g, err := filefield.Authorize(ctx, h.Store, documentAttachmentPolicy, input.Body)
	if err != nil {
		return nil, filefield.MapError(ctx, err)
	}
	return &uploadDocumentFileOutput{Body: contract.Data[filefield.UploadGrant]{Data: g}}, nil
}

type uploadDocumentCoverInput struct {
	Body filefield.UploadGrantRequest
}

// uploadCover grants the client one direct upload for the cover field:
// it sends the returned request, then creates the document with the key.
// Hooks with a BeforeUpload(ctx, field) method decide who may upload.
func (h *Handler) uploadCover(ctx context.Context, input *uploadDocumentCoverInput) (*uploadDocumentFileOutput, error) {
	if hk, ok := h.Hooks.(interface {
		BeforeUpload(ctx context.Context, field string) error
	}); ok {
		if err := hk.BeforeUpload(ctx, "cover"); err != nil {
			return nil, err
		}
	}
	g, err := filefield.Authorize(ctx, h.Store, documentCoverPolicy, input.Body)
	if err != nil {
		return nil, filefield.MapError(ctx, err)
	}
	return &uploadDocumentFileOutput{Body: contract.Data[filefield.UploadGrant]{Data: g}}, nil
}

// Register mounts document Huma routes, wiring the human-owned Hooks.
func Register(app *framework.App) {
	h := &Handler{DB: app.DB(), Hooks: Hooks{}, Store: app.Storage()}
	prefix := app.Config().API.Prefix
	api := app.API()

	huma.Register(api, huma.Operation{
		OperationID: "list-documents",
		Method:      http.MethodGet,
		Path:        prefix + "/documents",
		Summary:     "List documents",
		Tags:        []string{"Documents"},
	}, h.list)

	huma.Register(api, huma.Operation{
		OperationID: "get-document",
		Method:      http.MethodGet,
		Path:        prefix + "/documents/{id}",
		Summary:     "Get a document",
		Tags:        []string{"Documents"},
	}, h.get)

	huma.Register(api, huma.Operation{
		OperationID: "create-document",
		Method:      http.MethodPost,
		Path:        prefix + "/documents",
		Summary:     "Create a document",
		Tags:        []string{"Documents"},
	}, h.create)

	huma.Register(api, huma.Operation{
		OperationID: "upload-document-attachment",
		Method:      http.MethodPost,
		Path:        prefix + "/documents/uploads/attachment",
		Summary:     "Grant an upload of a document attachment",
		Tags:        []string{"Documents"},
	}, h.uploadAttachment)

	huma.Register(api, huma.Operation{
		OperationID: "upload-document-cover",
		Method:      http.MethodPost,
		Path:        prefix + "/documents/uploads/cover",
		Summary:     "Grant an upload of a document cover",
		Tags:        []string{"Documents"},
	}, h.uploadCover)

}
