// Package upload receives files from HTTP requests into a storage.Storage,
// safe by default:
//
//   - the file streams into the store; the request is never buffered, and
//     a file over Policy.MaxBytes fails as soon as the byte past the limit
//     arrives (or before a byte is read, when the declared length is over);
//   - the media type is detected from the file's first bytes and checked
//     against Policy.Types; the client's Content-Type and the filename's
//     extension are not trusted;
//   - the key is generated by the server (Policy.Prefix plus a random id),
//     so a client-controlled filename never becomes an object path: it is
//     kept, cleaned, as metadata (FilenameMetadata);
//   - a failed upload leaves nothing behind: a Put that fails stores
//     nothing (the storage contract); one whose outcome is unknown
//     (storage.ErrUnknownOutcome: a remote store may have stored it) has its
//     generated key deleted; and a file stored before the request turned
//     out to be invalid is deleted. When such a delete fails, the error
//     says which key may still hold a file (*CleanupError).
//
// Receive reads a multipart/form-data request (an HTML file input);
// ReceiveBody reads a request whose body is the file (PUT or POST with the
// file's bytes); Save applies the same policy to any reader. MapError turns
// their errors into D10 errors for a handler.
//
// Authorize and Confirm are the direct-upload flow, for files too large to
// pass through the application: Authorize grants the client one upload
// straight to the store (a signed PUT of a declared size and type, under a
// generated key); the client uploads; Confirm then checks what arrived,
// by its bytes, and deletes it if it breaks the policy.
package upload

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"maps"
	"math"
	"mime"
	"mime/multipart"
	"net/http"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/storage"
)

const (
	// DefaultField is the multipart form field Receive reads the file from
	// when Policy.Field is empty.
	DefaultField = "file"
	// FilenameMetadata is the metadata name the client's filename, cleaned,
	// is stored under (storage.FilenameMetadata).
	FilenameMetadata = storage.FilenameMetadata
	// MaxFilenameBytes bounds the stored filename; a longer one is cut at a
	// character boundary.
	MaxFilenameBytes = 255
	// SniffBytes is how many leading bytes a Detector sees (at most; fewer
	// when the file is shorter).
	SniffBytes = 512
	// MaxFormBytes bounds the rest of a multipart request, on its own: its
	// part headers, boundaries, and fields other than the file. A file
	// smaller than Policy.MaxBytes does not make room for more of them.
	MaxFormBytes = 64 << 10
	// idHexLen is the length of the random id a generated key ends with.
	idHexLen = 32
)

var (
	// ErrTooLarge: the file, or the request carrying it, is over the
	// policy's limit.
	ErrTooLarge = errors.New("upload: too large")
	// ErrType: the file's detected media type is not one the policy
	// accepts.
	ErrType = errors.New("upload: media type not allowed")
	// ErrNoFile: a multipart request has no file in the policy's field.
	ErrNoFile = errors.New("upload: no file")
	// ErrMalformed: the request is not a well-formed upload (not
	// multipart, a broken body, or more than one file).
	ErrMalformed = errors.New("upload: malformed request")
)

// CleanupError reports a key that may still hold a file after a failed
// upload: one stored before the request turned out to be invalid, or one a
// Put of unknown outcome may have stored, whose delete failed too. The
// upload's error carries it (errors.As) alongside the failure it reports,
// which it does not change; delete Key when the store is reachable again.
type CleanupError struct {
	Key string
	Err error // why the delete failed
}

func (e *CleanupError) Error() string {
	return fmt.Sprintf("upload: %q may still hold a file: deleting it failed: %v", e.Key, e.Err)
}

func (e *CleanupError) Unwrap() error { return e.Err }

// Detector returns a file's media type (with parameters, if any) from its
// first bytes: at most SniffBytes of them, fewer when the file is shorter.
// It gets a copy of them, its own to keep or change: nothing it does to it
// changes the file stored.
type Detector func(head []byte) string

// Policy is what an upload must satisfy and where it is stored.
type Policy struct {
	// MaxBytes is the largest file accepted, in bytes. Required.
	MaxBytes int64
	// Types lists the media types accepted, as detected from the file's
	// content: "image/png", or "image/*" for a whole top-level type.
	// Required: "*/*" accepts any type, and must be asked for.
	Types []string
	// Prefix starts every generated key ("avatars/"): empty, or a valid
	// key path ending with '/'. Set one for files a record owns: the
	// cleanup helpers (storage.DeleteOwned, storage.Sweep) work only under
	// a prefix, never on the whole store.
	Prefix string
	// Field is the multipart form field holding the file (DefaultField
	// when empty). Receive only.
	Field string
	// Detect detects the media type (http.DetectContentType when nil). The
	// default recognizes common images, audio, video, PDF, archives, and
	// fonts, and reports text as text/plain or text/html; it never reports
	// image/svg+xml or application/json. Supply a Detector for types it
	// does not recognize.
	Detect Detector
	// Metadata is stored with every file, besides FilenameMetadata (which
	// it must not set).
	Metadata map[string]string
	// GrantExpiry is how long a direct upload grant (Authorize) works
	// (DefaultGrantExpiry when zero; whole seconds, at most
	// storage.MaxURLExpiry, as for any signed URL).
	GrantExpiry time.Duration
}

// DefaultGrantExpiry is how long a direct upload grant works unless
// Policy.GrantExpiry says otherwise: long enough to start a large upload,
// short enough that a leaked grant is soon useless.
const DefaultGrantExpiry = 15 * time.Minute

// File is a stored upload. Its Filename() is the client's filename,
// cleaned (empty when it sent none): for display and Content-Disposition
// only, never a path.
type File struct {
	storage.ObjectInfo
}

func (p Policy) validate() error {
	switch {
	case p.MaxBytes <= 0:
		return errors.New("upload: Policy.MaxBytes must be positive")
	case p.MaxBytes > math.MaxInt64-MaxFormBytes:
		return fmt.Errorf("upload: Policy.MaxBytes must be at most %d", int64(math.MaxInt64-MaxFormBytes))
	case len(p.Types) == 0:
		return errors.New(`upload: Policy.Types must list the accepted media types ("*/*" for any)`)
	}
	// The keys are Prefix and a 32-character id: check that shape, so a
	// prefix the policy accepts gives keys every driver accepts.
	if err := storage.ValidatePrefix(p.Prefix); err != nil {
		return fmt.Errorf("upload: Policy.Prefix: %v", err) // the server's mistake, not an invalid request
	}
	if err := storage.ValidateKey(p.Prefix + strings.Repeat("0", idHexLen)); err != nil {
		return fmt.Errorf("upload: Policy.Prefix %q leaves no room for a generated key: %v", p.Prefix, err)
	}
	for _, t := range p.Types {
		if !validType(t) {
			return fmt.Errorf(`upload: Policy.Types entry %q: want a lowercase "type/subtype", "type/*", or "*/*"`, t)
		}
	}
	if p.GrantExpiry < 0 || p.GrantExpiry > storage.MaxURLExpiry || p.GrantExpiry%time.Second != 0 {
		return fmt.Errorf("upload: Policy.GrantExpiry must be whole seconds between 0 (the default) and %s, not %s", storage.MaxURLExpiry, p.GrantExpiry)
	}
	if _, ok := p.Metadata[FilenameMetadata]; ok {
		return fmt.Errorf("upload: Policy.Metadata must not set %q; the upload's filename goes there", FilenameMetadata)
	}
	if err := storage.ValidateMetadata(p.Metadata); err != nil {
		return fmt.Errorf("upload: Policy.Metadata: %v", err)
	}
	return nil
}

// validType reports whether t is a Policy.Types entry: a media type as
// mime.ParseMediaType reads one, without parameters, written exactly as it
// parses (lowercase, nothing around it), or a wildcard: "type/*" or "*/*".
// Anything else could never match a detected type.
func validType(t string) bool {
	mediaType, params, err := mime.ParseMediaType(t)
	if err != nil || len(params) != 0 || mediaType != t {
		return false
	}
	typ, sub, ok := strings.Cut(t, "/")
	if !ok || typ == "" || sub == "" || strings.Contains(sub, "/") {
		return false // ParseMediaType also accepts a bare "type"
	}
	switch {
	case typ == "*":
		return sub == "*"
	case strings.Contains(typ, "*"):
		return false
	case strings.Contains(sub, "*"):
		return sub == "*"
	}
	return true
}

// accepts reports whether the policy accepts the media type mediaType
// (lowercase, without parameters).
func (p Policy) accepts(mediaType string) bool {
	typ, _, _ := strings.Cut(mediaType, "/")
	for _, t := range p.Types {
		if t == "*/*" || t == mediaType || t == typ+"/*" {
			return true
		}
	}
	return false
}

// Save stores the file src under a generated key, applying p: its first
// bytes decide its media type, and it fails with ErrTooLarge at the byte
// past p.MaxBytes. filename is the client's name for it (metadata only;
// empty when none). A file Save refuses is not stored.
func Save(ctx context.Context, store storage.Storage, src io.Reader, filename string, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	return save(ctx, store, src, filename, nil, p)
}

// save is Save with an optional declared size, for a policy that has been
// validated.
func save(ctx context.Context, store storage.Storage, src io.Reader, filename string, size *int64, p Policy) (File, error) {
	source := &sourceReader{r: src}
	src = &limitReader{r: source, max: p.MaxBytes}
	head := make([]byte, SniffBytes)
	n, err := io.ReadFull(src, head)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return File{}, source.classify(ctx, err)
	}
	head = head[:n]
	detect := p.Detect
	if detect == nil {
		detect = http.DetectContentType
	}
	// The detector gets a copy: what it does with its argument (or keeps of
	// it) cannot reach the bytes stored.
	contentType := detect(bytes.Clone(head))
	mediaType, _, err := mime.ParseMediaType(contentType)
	if err != nil || !p.accepts(mediaType) {
		return File{}, fmt.Errorf("%w: detected %q", ErrType, contentType)
	}
	if err := storage.ValidatePutOptions(storage.PutOptions{ContentType: contentType}); err != nil {
		// An accepted type the store cannot record: the detector's mistake.
		return File{}, fmt.Errorf("upload: Policy.Detect returned %q: %v", contentType, err)
	}
	key, err := newKey(p.Prefix)
	if err != nil {
		return File{}, err
	}
	filename = CleanFilename(filename)
	md := maps.Clone(p.Metadata)
	if filename != "" {
		if md == nil {
			md = map[string]string{}
		}
		fitMetadata(md, filename)
	}
	info, err := store.Put(ctx, key, io.MultiReader(bytes.NewReader(head), src), storage.PutOptions{
		ContentType: contentType,
		Metadata:    md,
		Size:        size,
	})
	if errors.Is(err, storage.ErrUnknownOutcome) {
		// The store may hold the file under key: no one else will ever use
		// this key, so delete it, then report the failure as it now stands.
		if derr := discard(ctx, store, key); derr != nil {
			return File{}, errors.Join(source.classify(ctx, err), &CleanupError{Key: key, Err: derr})
		}
		return File{}, source.classify(ctx, settled(key, err))
	}
	if err != nil {
		return File{}, source.classify(ctx, err)
	}
	return File{ObjectInfo: info}, nil
}

// settled is a Put failure of unknown outcome whose key has since been
// deleted: nothing is stored, so it is reported as the transient failure
// it was (ctx's error, or storage.ErrUnavailable), no longer as
// storage.ErrUnknownOutcome. The original error stays in the message.
func settled(key string, err error) error {
	cause := storage.ErrUnavailable
	switch {
	case errors.Is(err, context.Canceled):
		cause = context.Canceled
	case errors.Is(err, context.DeadlineExceeded):
		cause = context.DeadlineExceeded
	}
	return storage.Wrap("put", key, fmt.Errorf("%w (%v; the key was then deleted, so nothing is stored)", cause, err))
}

// sourceReader remembers the first error its reader returned other than
// io.EOF: the client's body failing (a truncated or broken request), as
// opposed to the store failing.
type sourceReader struct {
	r   io.Reader
	err error
}

func (s *sourceReader) Read(p []byte) (int, error) {
	n, err := s.r.Read(p)
	if err != nil && !errors.Is(err, io.EOF) && s.err == nil {
		s.err = err
	}
	return n, err
}

// classify returns err, the reason an upload failed: with ctx's error when
// ctx has ended (the client went away, so its body failed too), and as
// ErrMalformed when the source failed first (unless it went over a limit).
func (s *sourceReader) classify(ctx context.Context, err error) error {
	if gone := clientGone(ctx, err); gone != nil {
		return gone
	}
	if s.err == nil || errors.Is(s.err, ErrTooLarge) {
		return err
	}
	return fmt.Errorf("%w: reading the file: %w", ErrMalformed, s.err)
}

// fitMetadata stores filename in md under FilenameMetadata, cut at a
// character boundary until md is valid, and returns what it stored.
func fitMetadata(md map[string]string, filename string) string {
	for filename != "" {
		md[FilenameMetadata] = filename
		if storage.ValidateMetadata(md) == nil {
			return filename
		}
		_, n := utf8.DecodeLastRuneInString(filename)
		filename = strings.TrimRightFunc(filename[:len(filename)-n], unicode.IsSpace)
	}
	delete(md, FilenameMetadata)
	return ""
}

// newKey returns prefix followed by a random 128-bit id, idHexLen hex
// characters.
func newKey(prefix string) (string, error) {
	var id [16]byte
	if _, err := rand.Read(id[:]); err != nil {
		return "", fmt.Errorf("upload: generate a key: %w", err)
	}
	return prefix + hex.EncodeToString(id[:]), nil
}

// CleanFilename returns a client-sent filename as safe metadata: its last
// path element (after '/' or '\'), without control, line-separator, or
// bidirectional-control characters, with "=?" (which metadata refuses)
// broken up, invalid UTF-8 replaced, surrounding space trimmed, and at most
// MaxFilenameBytes long. "." and ".." become empty. The result names a file
// for display; it is never an object key or a path.
func CleanFilename(name string) string {
	name = strings.ToValidUTF8(name, "�")
	if i := strings.LastIndexAny(name, `/\`); i >= 0 {
		name = name[i+1:]
	}
	name = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) || unicode.Is(unicode.Zl, r) || unicode.Is(unicode.Zp, r) || unicode.Is(unicode.Bidi_Control, r) {
			return -1
		}
		return r
	}, name)
	name = strings.ReplaceAll(name, "=?", "=_")
	if len(name) > MaxFilenameBytes {
		cut := MaxFilenameBytes
		for cut > 0 && !utf8.RuneStart(name[cut]) {
			cut--
		}
		name = name[:cut]
	}
	name = strings.TrimSpace(name)
	if name == "." || name == ".." {
		return ""
	}
	return name
}

// Receive stores the file of a multipart/form-data request (the part in
// p.Field with a filename; an empty file input sends none) and reads the
// rest of the request, so that a second file is refused. Everything but
// the file (part headers, boundaries, other fields) may be at most
// MaxFormBytes, on its own: other fields fail with ErrTooLarge as soon as
// they pass it, and the request as a whole is checked at its end, which is
// the end of the body (bytes after the closing boundary count too), not
// the closing boundary. The
// request may be at most p.MaxBytes plus MaxFormBytes long: a longer
// declared length fails before a byte is read, and a longer body when it
// gets there. If the request turns out to be invalid after the file was
// stored, the file is deleted.
func Receive(store storage.Storage, r *http.Request, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	limit := p.MaxBytes + MaxFormBytes
	if r.ContentLength > limit {
		return File{}, fmt.Errorf("%w: the request is %d bytes, more than %d", ErrTooLarge, r.ContentLength, limit)
	}
	ctx := r.Context()
	mr, body, err := multipartReader(r, limit)
	if err != nil {
		return File{}, err
	}
	field := p.Field
	if field == "" {
		field = DefaultField
	}
	var file File
	stored := false
	var fileBytes, fieldBytes int64 // the file's bytes; other fields' bytes
	fail := func(err error) (File, error) {
		if stored {
			if derr := discard(ctx, store, file.Key); derr != nil {
				err = errors.Join(err, &CleanupError{Key: file.Key, Err: derr})
			}
		}
		return File{}, err
	}
	for {
		part, err := mr.NextPart()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fail(malformed(ctx, err))
		}
		if part.FormName() != field || part.FileName() == "" {
			n, err := io.Copy(io.Discard, io.LimitReader(part, MaxFormBytes-fieldBytes+1))
			fieldBytes += n
			if err != nil {
				return fail(malformed(ctx, err))
			}
			if fieldBytes > MaxFormBytes {
				return fail(formTooLarge())
			}
			continue
		}
		if stored {
			return fail(fmt.Errorf("%w: more than one file in %q", ErrMalformed, field))
		}
		counted := &countReader{r: part}
		file, err = save(ctx, store, counted, part.FileName(), nil, p)
		if err != nil {
			return fail(err)
		}
		stored = true
		fileBytes = counted.n
	}
	// The parser stops at the closing boundary; the request goes on to the
	// end of its body (the MIME epilogue), and that is form overhead too.
	// Read it to the end, within what is left of MaxFormBytes (and of the
	// request's limit, which body enforces), then check the whole request.
	if left := MaxFormBytes - (body.read - fileBytes); left >= 0 {
		if _, err := io.Copy(io.Discard, io.LimitReader(body, left+1)); err != nil {
			return fail(malformed(ctx, err))
		}
	}
	if body.read-fileBytes > MaxFormBytes {
		return fail(formTooLarge())
	}
	// The body may have failed in a Read whose bytes the parser used (a body
	// cut short ends with its last bytes and io.ErrUnexpectedEOF together):
	// the request failed, whatever the multipart entity looked like.
	if body.err != nil {
		return fail(malformed(ctx, body.err))
	}
	if !stored {
		return File{}, fmt.Errorf("%w in the form field %q", ErrNoFile, field)
	}
	return file, nil
}

func formTooLarge() error {
	return fmt.Errorf("%w: the form's fields other than the file are more than %d bytes", ErrTooLarge, MaxFormBytes)
}

// countReader counts the bytes read through it.
type countReader struct {
	r io.Reader
	n int64
}

func (c *countReader) Read(p []byte) (int, error) {
	n, err := c.r.Read(p)
	c.n += int64(n)
	return n, err
}

// ReceiveBody stores a request's body as the file: its declared length, if
// any, must be at most p.MaxBytes (checked before a byte is read) and must
// match the body. The filename, if any, is the filename parameter of the
// request's Content-Disposition header; the Content-Type header is not
// trusted.
func ReceiveBody(store storage.Storage, r *http.Request, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	if r.ContentLength > p.MaxBytes {
		return File{}, fmt.Errorf("%w: %d bytes, more than %d", ErrTooLarge, r.ContentLength, p.MaxBytes)
	}
	var filename string
	if _, params, err := mime.ParseMediaType(r.Header.Get("Content-Disposition")); err == nil {
		filename = params["filename"]
	}
	body := io.Reader(http.NoBody)
	if r.Body != nil {
		body = r.Body
	}
	return save(r.Context(), store, body, filename, storage.SizeFromContentLength(r.ContentLength), p)
}

// multipartReader returns the multipart reader of r, whose body it limits
// to limit bytes, and that limited body (whose read count is the bytes
// consumed). r is marked as read, as by r.MultipartReader: a later
// ParseMultipartForm on it fails plainly instead of parsing a drained body.
func multipartReader(r *http.Request, limit int64) (*multipart.Reader, *limitReader, error) {
	if r.Body == nil {
		return nil, nil, fmt.Errorf("%w: no body", ErrMalformed)
	}
	body := &limitReader{r: r.Body, max: limit}
	r.Body = struct {
		io.Reader
		io.Closer
	}{body, r.Body}
	mr, err := r.MultipartReader()
	if err != nil {
		return nil, nil, fmt.Errorf("%w: %w", ErrMalformed, err)
	}
	return mr, body, nil
}

// malformed classifies a failure reading a multipart request, at any point
// of it (a part's headers, a field other than the file, after the closing
// boundary), the way sourceReader.classify does while the file is read: the
// context's error first when the request's context has ended (the client
// went away, so its body failed too), ErrTooLarge past the request's
// limit, otherwise ErrMalformed.
func malformed(ctx context.Context, err error) error {
	if gone := clientGone(ctx, err); gone != nil {
		return gone
	}
	if errors.Is(err, ErrTooLarge) {
		return err
	}
	return fmt.Errorf("%w: %w", ErrMalformed, err)
}

// clientGone returns err as the request context's error when that context
// has ended (the client went away or the request timed out, so whatever
// failed reading its body failed because of it), or nil when it has not.
// Every read failure of an upload is classified through it first.
func clientGone(ctx context.Context, err error) error {
	cerr := ctx.Err()
	switch {
	case cerr == nil:
		return nil
	case errors.Is(err, cerr):
		return err
	}
	return fmt.Errorf("%w: %w", cerr, err)
}

// discard deletes a stored file that turned out to be part of an invalid
// request, even when the request's context has ended (a client that went
// away mid-request).
func discard(ctx context.Context, store storage.Storage, key string) error {
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
	defer cancel()
	return store.Delete(ctx, key)
}

// limitReader fails with ErrTooLarge once more than max bytes come
// through. It remembers the first error its reader returned other than
// io.EOF (err): a buffered reader above it (multipart's) may hand out the
// bytes that came with an error and keep the error, so the failure has to
// be recorded here, where it passed.
type limitReader struct {
	r    io.Reader
	max  int64
	read int64
	err  error
}

func (l *limitReader) Read(p []byte) (int, error) {
	if l.read > l.max {
		return 0, l.tooLarge()
	}
	if left := l.max - l.read + 1; int64(len(p)) > left {
		p = p[:left] // one byte past max is enough to know
	}
	n, err := l.r.Read(p)
	l.read += int64(n)
	if err != nil && !errors.Is(err, io.EOF) && l.err == nil {
		l.err = err
	}
	if l.read > l.max {
		return 0, l.tooLarge()
	}
	return n, err
}

func (l *limitReader) tooLarge() error {
	return fmt.Errorf("%w: more than %d bytes", ErrTooLarge, l.max)
}

// MapError maps an upload error to a D10 error for a handler: ErrTooLarge
// (or an http.MaxBytesError) is 413 payload_too_large; ErrType, ErrNoFile,
// and ErrMalformed are validation errors; anything else is a storage error
// (storage.MapError).
func MapError(ctx context.Context, err error) error {
	var maxBytes *http.MaxBytesError
	switch {
	case err == nil:
		return nil
	case errors.Is(err, ErrTooLarge), errors.As(err, &maxBytes):
		return contract.WithContext(ctx, contract.PayloadTooLarge("The file is too large."))
	case errors.Is(err, ErrType):
		return contract.WithContext(ctx, contract.Validation("The file's type is not allowed.", nil))
	case errors.Is(err, ErrNoFile):
		return contract.WithContext(ctx, contract.Validation("No file was uploaded.", nil))
	case errors.Is(err, ErrMalformed):
		return contract.WithContext(ctx, contract.Validation("The upload could not be read.", nil))
	}
	return storage.MapError(ctx, err, "file not found", "could not store the file")
}
