// Package upload receives files from HTTP requests into a storage.Storage,
// safe by default:
//
//   - the file streams into the store; the request is never buffered, and
//     a file over Policy.MaxBytes fails as soon as the byte past the limit
//     arrives (or before a byte is read, when the declared length is over);
//   - the media type is detected from the file's first bytes and checked
//     against Policy.Types; the client's Content-Type and the filename's
//     extension are not trusted;
//   - the key is generated by the server (Policy.Prefix plus a random id),
//     so a client-controlled filename never becomes an object path: it is
//     kept, cleaned, as metadata (FilenameMetadata);
//   - a failed upload leaves nothing behind: a Put that fails stores
//     nothing (the storage contract), and a file stored before the request
//     turned out to be invalid is deleted.
//
// Receive reads a multipart/form-data request (an HTML file input);
// ReceiveBody reads a request whose body is the file (PUT or POST with the
// file's bytes); Save applies the same policy to any reader. MapError turns
// their errors into D10 errors for a handler.
//
// Authorize and Confirm are the direct-upload flow, for files too large to
// pass through the application: Authorize grants the client one upload
// straight to the store (a signed PUT of a declared size and type, under a
// generated key); the client uploads; Confirm then checks what arrived,
// by its bytes, and deletes it if it breaks the policy.
package upload

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"maps"
	"math"
	"mime"
	"mime/multipart"
	"net/http"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/storage"
)

const (
	// DefaultField is the multipart form field Receive reads the file from
	// when Policy.Field is empty.
	DefaultField = "file"
	// FilenameMetadata is the metadata name the client's filename, cleaned,
	// is stored under (storage.FilenameMetadata).
	FilenameMetadata = storage.FilenameMetadata
	// MaxFilenameBytes bounds the stored filename; a longer one is cut at a
	// character boundary.
	MaxFilenameBytes = 255
	// SniffBytes is how many leading bytes a Detector sees (at most; fewer
	// when the file is shorter).
	SniffBytes = 512
	// MaxFormBytes bounds the rest of a multipart request: its part
	// headers, boundaries, and fields other than the file.
	MaxFormBytes = 64 << 10
)

var (
	// ErrTooLarge: the file, or the request carrying it, is over the
	// policy's limit.
	ErrTooLarge = errors.New("upload: too large")
	// ErrType: the file's detected media type is not one the policy
	// accepts.
	ErrType = errors.New("upload: media type not allowed")
	// ErrNoFile: a multipart request has no file in the policy's field.
	ErrNoFile = errors.New("upload: no file")
	// ErrMalformed: the request is not a well-formed upload (not
	// multipart, a broken body, or more than one file).
	ErrMalformed = errors.New("upload: malformed request")
)

// Detector returns a file's media type (with parameters, if any) from its
// first bytes: at most SniffBytes of them, fewer when the file is shorter.
type Detector func(head []byte) string

// Policy is what an upload must satisfy and where it is stored.
type Policy struct {
	// MaxBytes is the largest file accepted, in bytes. Required.
	MaxBytes int64
	// Types lists the media types accepted, as detected from the file's
	// content: "image/png", or "image/*" for a whole top-level type.
	// Required: "*/*" accepts any type, and must be asked for.
	Types []string
	// Prefix starts every generated key ("avatars/"): empty, or a valid
	// key path ending with '/'. Set one for files a record owns: the
	// cleanup helpers (storage.DeleteOwned, storage.Sweep) work only under
	// a prefix, never on the whole store.
	Prefix string
	// Field is the multipart form field holding the file (DefaultField
	// when empty). Receive only.
	Field string
	// Detect detects the media type (http.DetectContentType when nil). The
	// default recognizes common images, audio, video, PDF, archives, and
	// fonts, and reports text as text/plain or text/html; it never reports
	// image/svg+xml or application/json. Supply a Detector for types it
	// does not recognize.
	Detect Detector
	// Metadata is stored with every file, besides FilenameMetadata (which
	// it must not set).
	Metadata map[string]string
	// GrantExpiry is how long a direct upload grant (Authorize) works
	// (DefaultGrantExpiry when zero; at most storage.MaxURLExpiry).
	GrantExpiry time.Duration
}

// DefaultGrantExpiry is how long a direct upload grant works unless
// Policy.GrantExpiry says otherwise: long enough to start a large upload,
// short enough that a leaked grant is soon useless.
const DefaultGrantExpiry = 15 * time.Minute

// File is a stored upload. Its Filename() is the client's filename,
// cleaned (empty when it sent none): for display and Content-Disposition
// only, never a path.
type File struct {
	storage.ObjectInfo
}

func (p Policy) validate() error {
	switch {
	case p.MaxBytes <= 0:
		return errors.New("upload: Policy.MaxBytes must be positive")
	case p.MaxBytes > math.MaxInt64-MaxFormBytes:
		return fmt.Errorf("upload: Policy.MaxBytes must be at most %d", int64(math.MaxInt64-MaxFormBytes))
	case len(p.Types) == 0:
		return errors.New(`upload: Policy.Types must list the accepted media types ("*/*" for any)`)
	case p.Prefix != "" && !strings.HasSuffix(p.Prefix, "/"):
		return fmt.Errorf("upload: Policy.Prefix %q must end with '/'", p.Prefix)
	}
	if p.Prefix != "" {
		if err := storage.ValidateKey(p.Prefix + "id"); err != nil {
			return fmt.Errorf("upload: Policy.Prefix %q: %v", p.Prefix, err) // the server's mistake, not an invalid request
		}
	}
	for _, t := range p.Types {
		typ, sub, ok := strings.Cut(t, "/")
		if !ok || typ == "" || sub == "" || t != strings.ToLower(t) || strings.ContainsAny(t, "; \t") || (typ == "*" && sub != "*") {
			return fmt.Errorf(`upload: Policy.Types entry %q: want a lowercase "type/subtype", "type/*", or "*/*"`, t)
		}
	}
	if p.GrantExpiry < 0 || p.GrantExpiry > storage.MaxURLExpiry {
		return fmt.Errorf("upload: Policy.GrantExpiry must be between 0 (the default) and %s", storage.MaxURLExpiry)
	}
	if _, ok := p.Metadata[FilenameMetadata]; ok {
		return fmt.Errorf("upload: Policy.Metadata must not set %q; the upload's filename goes there", FilenameMetadata)
	}
	if err := storage.ValidateMetadata(p.Metadata); err != nil {
		return fmt.Errorf("upload: Policy.Metadata: %v", err)
	}
	return nil
}

// accepts reports whether the policy accepts the media type mediaType
// (lowercase, without parameters).
func (p Policy) accepts(mediaType string) bool {
	typ, _, _ := strings.Cut(mediaType, "/")
	for _, t := range p.Types {
		if t == "*/*" || t == mediaType || t == typ+"/*" {
			return true
		}
	}
	return false
}

// Save stores the file src under a generated key, applying p: its first
// bytes decide its media type, and it fails with ErrTooLarge at the byte
// past p.MaxBytes. filename is the client's name for it (metadata only;
// empty when none). A file Save refuses is not stored.
func Save(ctx context.Context, store storage.Storage, src io.Reader, filename string, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	return save(ctx, store, src, filename, nil, p)
}

// save is Save with an optional declared size, for a policy that has been
// validated.
func save(ctx context.Context, store storage.Storage, src io.Reader, filename string, size *int64, p Policy) (File, error) {
	source := &sourceReader{r: src}
	src = &limitReader{r: source, max: p.MaxBytes}
	head := make([]byte, SniffBytes)
	n, err := io.ReadFull(src, head)
	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, io.ErrUnexpectedEOF) {
		return File{}, source.classify(ctx, err)
	}
	head = head[:n]
	detect := p.Detect
	if detect == nil {
		detect = http.DetectContentType
	}
	contentType := detect(head)
	mediaType, _, err := mime.ParseMediaType(contentType)
	if err != nil || !p.accepts(mediaType) {
		return File{}, fmt.Errorf("%w: detected %q", ErrType, contentType)
	}
	if err := storage.ValidatePutOptions(storage.PutOptions{ContentType: contentType}); err != nil {
		// An accepted type the store cannot record: the detector's mistake.
		return File{}, fmt.Errorf("upload: Policy.Detect returned %q: %v", contentType, err)
	}
	key, err := newKey(p.Prefix)
	if err != nil {
		return File{}, err
	}
	filename = CleanFilename(filename)
	md := maps.Clone(p.Metadata)
	if filename != "" {
		if md == nil {
			md = map[string]string{}
		}
		fitMetadata(md, filename)
	}
	info, err := store.Put(ctx, key, io.MultiReader(bytes.NewReader(head), src), storage.PutOptions{
		ContentType: contentType,
		Metadata:    md,
		Size:        size,
	})
	if err != nil {
		return File{}, source.classify(ctx, err)
	}
	return File{ObjectInfo: info}, nil
}

// sourceReader remembers the first error its reader returned other than
// io.EOF: the client's body failing (a truncated or broken request), as
// opposed to the store failing.
type sourceReader struct {
	r   io.Reader
	err error
}

func (s *sourceReader) Read(p []byte) (int, error) {
	n, err := s.r.Read(p)
	if err != nil && !errors.Is(err, io.EOF) && s.err == nil {
		s.err = err
	}
	return n, err
}

// classify returns err, the reason an upload failed: with ctx's error when
// ctx has ended (the client went away, so its body failed too), and as
// ErrMalformed when the source failed first (unless it went over a limit).
func (s *sourceReader) classify(ctx context.Context, err error) error {
	if cerr := ctx.Err(); cerr != nil {
		if errors.Is(err, cerr) {
			return err
		}
		return fmt.Errorf("%w: %w", cerr, err)
	}
	if s.err == nil || errors.Is(s.err, ErrTooLarge) {
		return err
	}
	return fmt.Errorf("%w: reading the file: %w", ErrMalformed, s.err)
}

// fitMetadata stores filename in md under FilenameMetadata, cut at a
// character boundary until md is valid, and returns what it stored.
func fitMetadata(md map[string]string, filename string) string {
	for filename != "" {
		md[FilenameMetadata] = filename
		if storage.ValidateMetadata(md) == nil {
			return filename
		}
		_, n := utf8.DecodeLastRuneInString(filename)
		filename = strings.TrimRightFunc(filename[:len(filename)-n], unicode.IsSpace)
	}
	delete(md, FilenameMetadata)
	return ""
}

// newKey returns prefix followed by a random 128-bit id.
func newKey(prefix string) (string, error) {
	var id [16]byte
	if _, err := rand.Read(id[:]); err != nil {
		return "", fmt.Errorf("upload: generate a key: %w", err)
	}
	return prefix + hex.EncodeToString(id[:]), nil
}

// CleanFilename returns a client-sent filename as safe metadata: its last
// path element (after '/' or '\'), without control, line-separator, or
// bidirectional-control characters, with "=?" (which metadata refuses)
// broken up, invalid UTF-8 replaced, surrounding space trimmed, and at most
// MaxFilenameBytes long. "." and ".." become empty. The result names a file
// for display; it is never an object key or a path.
func CleanFilename(name string) string {
	name = strings.ToValidUTF8(name, "�")
	if i := strings.LastIndexAny(name, `/\`); i >= 0 {
		name = name[i+1:]
	}
	name = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) || unicode.Is(unicode.Zl, r) || unicode.Is(unicode.Zp, r) || unicode.Is(unicode.Bidi_Control, r) {
			return -1
		}
		return r
	}, name)
	name = strings.ReplaceAll(name, "=?", "=_")
	if len(name) > MaxFilenameBytes {
		cut := MaxFilenameBytes
		for cut > 0 && !utf8.RuneStart(name[cut]) {
			cut--
		}
		name = name[:cut]
	}
	name = strings.TrimSpace(name)
	if name == "." || name == ".." {
		return ""
	}
	return name
}

// Receive stores the file of a multipart/form-data request (the part in
// p.Field with a filename; an empty file input sends none) and reads the
// rest of the request, so that a second file is refused. The request may
// be at most p.MaxBytes plus MaxFormBytes long: a longer declared length
// fails before a byte is read, and a longer body when it gets there. If the
// request turns out to be invalid after the file was stored, the file is
// deleted.
func Receive(store storage.Storage, r *http.Request, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	limit := p.MaxBytes + MaxFormBytes
	if r.ContentLength > limit {
		return File{}, fmt.Errorf("%w: the request is %d bytes, more than %d", ErrTooLarge, r.ContentLength, limit)
	}
	ctx := r.Context()
	mr, err := multipartReader(r, limit)
	if err != nil {
		return File{}, err
	}
	field := p.Field
	if field == "" {
		field = DefaultField
	}
	var file File
	stored := false
	fail := func(err error) (File, error) {
		if stored {
			if derr := discard(ctx, store, file.Key); derr != nil {
				err = errors.Join(err, fmt.Errorf("upload: delete the stored file %q: %w", file.Key, derr))
			}
		}
		return File{}, err
	}
	for {
		part, err := mr.NextPart()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fail(malformed(err))
		}
		if part.FormName() != field || part.FileName() == "" {
			if _, err := io.Copy(io.Discard, part); err != nil {
				return fail(malformed(err))
			}
			continue
		}
		if stored {
			return fail(fmt.Errorf("%w: more than one file in %q", ErrMalformed, field))
		}
		file, err = save(ctx, store, part, part.FileName(), nil, p)
		if err != nil {
			return fail(err)
		}
		stored = true
	}
	if !stored {
		return File{}, fmt.Errorf("%w in the form field %q", ErrNoFile, field)
	}
	return file, nil
}

// ReceiveBody stores a request's body as the file: its declared length, if
// any, must be at most p.MaxBytes (checked before a byte is read) and must
// match the body. The filename, if any, is the filename parameter of the
// request's Content-Disposition header; the Content-Type header is not
// trusted.
func ReceiveBody(store storage.Storage, r *http.Request, p Policy) (File, error) {
	if err := p.validate(); err != nil {
		return File{}, err
	}
	if r.ContentLength > p.MaxBytes {
		return File{}, fmt.Errorf("%w: %d bytes, more than %d", ErrTooLarge, r.ContentLength, p.MaxBytes)
	}
	var filename string
	if _, params, err := mime.ParseMediaType(r.Header.Get("Content-Disposition")); err == nil {
		filename = params["filename"]
	}
	body := io.Reader(http.NoBody)
	if r.Body != nil {
		body = r.Body
	}
	return save(r.Context(), store, body, filename, storage.SizeFromContentLength(r.ContentLength), p)
}

// multipartReader returns the multipart reader of r, whose body it limits
// to limit bytes. r is marked as read, as by r.MultipartReader: a later
// ParseMultipartForm on it fails plainly instead of parsing a drained body.
func multipartReader(r *http.Request, limit int64) (*multipart.Reader, error) {
	if r.Body == nil {
		return nil, fmt.Errorf("%w: no body", ErrMalformed)
	}
	r.Body = struct {
		io.Reader
		io.Closer
	}{&limitReader{r: r.Body, max: limit}, r.Body}
	mr, err := r.MultipartReader()
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrMalformed, err)
	}
	return mr, nil
}

// malformed classifies an error reading a multipart request's structure:
// ErrTooLarge past the request's limit, otherwise ErrMalformed.
func malformed(err error) error {
	if errors.Is(err, ErrTooLarge) {
		return err
	}
	return fmt.Errorf("%w: %w", ErrMalformed, err)
}

// discard deletes a stored file that turned out to be part of an invalid
// request, even when the request's context has ended (a client that went
// away mid-request).
func discard(ctx context.Context, store storage.Storage, key string) error {
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
	defer cancel()
	return store.Delete(ctx, key)
}

// limitReader fails with ErrTooLarge once more than max bytes come
// through.
type limitReader struct {
	r    io.Reader
	max  int64
	read int64
}

func (l *limitReader) Read(p []byte) (int, error) {
	if l.read > l.max {
		return 0, l.tooLarge()
	}
	if left := l.max - l.read + 1; int64(len(p)) > left {
		p = p[:left] // one byte past max is enough to know
	}
	n, err := l.r.Read(p)
	l.read += int64(n)
	if l.read > l.max {
		return 0, l.tooLarge()
	}
	return n, err
}

func (l *limitReader) tooLarge() error {
	return fmt.Errorf("%w: more than %d bytes", ErrTooLarge, l.max)
}

// MapError maps an upload error to a D10 error for a handler: ErrTooLarge
// (or an http.MaxBytesError) is 413 payload_too_large; ErrType, ErrNoFile,
// and ErrMalformed are validation errors; anything else is a storage error
// (storage.MapError).
func MapError(ctx context.Context, err error) error {
	var maxBytes *http.MaxBytesError
	switch {
	case err == nil:
		return nil
	case errors.Is(err, ErrTooLarge), errors.As(err, &maxBytes):
		return contract.WithContext(ctx, contract.PayloadTooLarge("The file is too large."))
	case errors.Is(err, ErrType):
		return contract.WithContext(ctx, contract.Validation("The file's type is not allowed.", nil))
	case errors.Is(err, ErrNoFile):
		return contract.WithContext(ctx, contract.Validation("No file was uploaded.", nil))
	case errors.Is(err, ErrMalformed):
		return contract.WithContext(ctx, contract.Validation("The upload could not be read.", nil))
	}
	return storage.MapError(ctx, err, "file not found", "could not store the file")
}
