// Code generated by gombit make resource. DO NOT EDIT.
package book

import (
	"os"
	"testing"

	"github.com/gombit-dev/gombit/resourcecheck"
)

// TestBookContractMatchesModel guards against the Book schema and the
// generated API contract drifting apart (#218): a column the create handler
// cannot supply would be silently zero-filled, and a model field missing from
// the request/response wire contract would be rejected on input or never
// returned. When this fails after you change Book, update the constructor or
// DTOs, or declare the column in the opt-out lists in book_contract.go.
func TestBookContractMatchesModel(t *testing.T) {
	src, err := os.ReadFile("handler.go")
	if err != nil {
		t.Fatalf("read handler.go: %v", err)
	}
	// (1) The static checks below are sound only if the create handler matches
	// the canonical generated grammar (row := buildBookForCreate(ctx, input);
	// h.DB.….Create(&row)); a refactor outside it is reported, not assumed safe.
	if ok, detail, perr := resourcecheck.ValidateCreateGrammar(src, "Handler", "create", "buildBookForCreate", "Book"); perr != nil {
		t.Fatalf("inspect Book create handler: %v", perr)
	} else if !ok {
		t.Fatalf("%s", detail)
	}
	assigned, err := resourcecheck.ConstructorCreateFields(src, "buildBookForCreate", "Book")
	if err != nil {
		t.Fatalf("parse Book create constructor: %v", err)
	}
	// (2) Every persistence-required column has a known create-value source.
	missing, err := resourcecheck.MissingCreateColumns(&Book{}, assigned, bookServerManagedColumns)
	if err != nil {
		t.Fatalf("inspect Book schema: %v", err)
	}
	for _, column := range missing {
		t.Errorf("create drift: Book.%s is NOT NULL with no default but is neither assigned by the create constructor nor in bookServerManagedColumns", column)
	}
	// (3) Every DB-backed content column is exposed by the create request and
	// read response wire contract (the actual DTO types h.create/h.get use),
	// unless explicitly opted out.
	h := &Handler{}
	writeDrift, readDrift, err := resourcecheck.ModelWireDrift(&Book{}, h.create, h.get, bookServerManagedColumns, bookWriteOmittedColumns, bookReadOmittedColumns)
	if err != nil {
		t.Fatalf("compare Book model with wire contract: %v", err)
	}
	for _, column := range writeDrift {
		t.Errorf("input drift: Book.%s is not settable via the create request; add it to the create request body, or list its column in bookServerManagedColumns / bookWriteOmittedColumns", column)
	}
	for _, column := range readDrift {
		t.Errorf("response drift: Book.%s is never surfaced; add it to the response DTO, or list its column in bookReadOmittedColumns", column)
	}
}
