// Code generated by gombit make resource. DO NOT EDIT.
package book

import "gorm.io/gorm"

// Book is the feature-package GORM model.
type Book struct {
	gorm.Model
	Title string `gorm:"size:255;not null"`
}
