// Code generated by gombit make resource. DO NOT EDIT.
package book

import (
	"testing"

	"github.com/gombit-dev/gombit/resourcecheck"
)

// bookServerManagedColumns lists NOT NULL columns the create handler fills
// server-side (e.g. from the auth context or a hook) instead of from the
// request body. Add a column here when you set it in code; the drift test
// then treats it as a known source.
var bookServerManagedColumns = []string{}

// TestBookCreateContractCoversRequiredColumns guards against the Book
// schema and the generated create contract drifting into an invalid state
// (#218): a NOT NULL column with no database default that is neither writable
// via createBookInput nor server-managed would be silently zero-filled on
// create. When this fails after you add a column to Book, either add the
// field to createBookInput (and its write path in the handler), set it
// server-side and list its column in bookServerManagedColumns, or make the column
// nullable.
func TestBookCreateContractCoversRequiredColumns(t *testing.T) {
	drift, err := resourcecheck.MissingCreateColumns(&Book{}, createBookInput{}.Body, bookServerManagedColumns)
	if err != nil {
		t.Fatalf("inspect Book schema: %v", err)
	}
	for _, column := range drift {
		t.Errorf("model/handler drift: Book.%s is NOT NULL with no default but is not writable via createBookInput and not server-managed", column)
	}
}
