// Code generated by gombit make resource. DO NOT EDIT.
package book

import (
	"context"
	"strconv"

	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/database"
	"gorm.io/gorm"
)

// Handler serves book HTTP operations over GORM.
type Handler struct {
	DB *gorm.DB
}

type bookData struct {
	ID    uint   `json:"id" example:"1" doc:"Book identifier"`
	Title string `json:"title" doc:"Title"`
}

type listBooksOutput struct {
	Body contract.DataMeta[[]bookData, contract.PageMeta]
}

type listBooksInput struct {
	Page    int `query:"page" doc:"1-based page"`
	PerPage int `query:"per_page" doc:"Page size"`
}

type getBookInput struct {
	ID string `path:"id" doc:"Book identifier"`
}

type getBookOutput struct {
	Body contract.Data[bookData]
}

type createBookInput struct {
	Body struct {
		Title string `json:"title" minLength:"1" maxLength:"255" doc:"Title"`
	}
}

type createBookOutput struct {
	Body contract.Data[bookData]
}

func (h *Handler) list(ctx context.Context, input *listBooksInput) (*listBooksOutput, error) {
	page, perPage := contract.ClampPage(input.Page, input.PerPage)
	q := h.DB.WithContext(ctx).Model(&Book{})
	var total int64
	if err := q.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list books"))
	}
	var rows []Book
	if err := q.Order("id").Offset(contract.PageOffset(page, perPage)).Limit(perPage).Find(&rows).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list books"))
	}
	items := make([]bookData, 0, len(rows))
	for _, row := range rows {
		items = append(items, toBookData(row))
	}
	return &listBooksOutput{
		Body: contract.DataMeta[[]bookData, contract.PageMeta]{
			Data: items,
			Meta: &contract.PageMeta{Page: page, PerPage: perPage, Total: total},
		},
	}, nil
}

func (h *Handler) get(ctx context.Context, input *getBookInput) (*getBookOutput, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, contract.WithContext(ctx, contract.NotFound("book not found"))
	}
	var row Book
	if err := h.DB.WithContext(ctx).First(&row, uint(id)).Error; err != nil {
		return nil, database.MapLoadError(ctx, err, "book not found", "load book")
	}
	return &getBookOutput{
		Body: contract.Data[bookData]{Data: toBookData(row)},
	}, nil
}

func (h *Handler) create(ctx context.Context, input *createBookInput) (*createBookOutput, error) {
	row := Book{
		Title: input.Body.Title,
	}
	if err := h.DB.WithContext(ctx).Create(&row).Error; err != nil {
		return nil, database.MapPersistError(ctx, err, "resource already exists", "create book")
	}
	return &createBookOutput{
		Body: contract.Data[bookData]{Data: toBookData(row)},
	}, nil
}

func toBookData(row Book) bookData {
	return bookData{ID: row.ID, Title: row.Title}
}
