// Code generated by gombit make resource. DO NOT EDIT.
package book

import (
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	"github.com/gombit-dev/gombit/framework"
)

// Register mounts book Huma routes. Called explicitly from main; Gombit
// does not discover feature packages by reflection.
func Register(app *framework.App) {
	h := &Handler{DB: app.DB()}
	prefix := app.Config().API.Prefix
	api := app.API()

	huma.Register(api, huma.Operation{
		OperationID: "list-books",
		Method:      http.MethodGet,
		Path:        prefix + "/books",
		Summary:     "List books",
		Tags:        []string{"Books"},
	}, h.list)

	huma.Register(api, huma.Operation{
		OperationID: "get-book",
		Method:      http.MethodGet,
		Path:        prefix + "/books/{id}",
		Summary:     "Get a book",
		Tags:        []string{"Books"},
	}, h.get)

	huma.Register(api, huma.Operation{
		OperationID: "create-book",
		Method:      http.MethodPost,
		Path:        prefix + "/books",
		Summary:     "Create a book",
		Tags:        []string{"Books"},
	}, h.create)
}
