// Code generated by gombit make resource. DO NOT EDIT.
package task

import time "time"

// taskData is the response body for a Task.
type taskData struct {
	ID        uint      `json:"id" doc:"ID"`
	CreatedAt time.Time `json:"created_at" doc:"CreatedAt"`
	UpdatedAt time.Time `json:"updated_at" doc:"UpdatedAt"`
	Title     string    `json:"title" doc:"Title"`
	Done      bool      `json:"done" doc:"Done"`
}

// taskCreateBody is the request body for creating a Task.
type taskCreateBody struct {
	Title string `json:"title" minLength:"1" maxLength:"255" doc:"Title"`
	Done  bool   `json:"done" doc:"Done"`
}

// toTaskData projects a Task into its response DTO.
func toTaskData(row Task) taskData {
	return taskData{
		ID:        row.Model.ID,
		CreatedAt: row.Model.CreatedAt,
		UpdatedAt: row.Model.UpdatedAt,
		Title:     row.Title,
		Done:      row.Done,
	}
}

// taskFromCreateBody builds a new Task from a create request.
func taskFromCreateBody(body taskCreateBody) Task {
	var row Task
	row.Title = body.Title
	row.Done = body.Done
	return row
}
