// Code generated by gombit make resource. DO NOT EDIT.
package task

import (
	"context"
	"net/http"
	"strconv"

	"github.com/danielgtaylor/huma/v2"
	"github.com/gombit-dev/gombit/contract"
	"github.com/gombit-dev/gombit/database"
	"github.com/gombit-dev/gombit/framework"
	"gorm.io/gorm"
)

// TaskHooks are the customization points for the generated Task handler.
// The generated handler owns the invariant CRUD sequence and calls these; set
// server-managed columns (tenant, owner, …) in BeforeCreate rather than editing
// generated plumbing.
type TaskHooks interface {
	BeforeCreate(ctx context.Context, row *Task, body taskCreateBody) error
}

// Handler serves Task HTTP operations over GORM. Register wires DB and Hooks.
type Handler struct {
	DB    *gorm.DB
	Hooks TaskHooks
}

type listTasksOutput struct {
	Body contract.DataMeta[[]taskData, contract.PageMeta]
}

type listTasksInput struct {
	Page    int `query:"page" doc:"1-based page"`
	PerPage int `query:"per_page" doc:"Page size"`
}

type getTaskInput struct {
	ID string `path:"id" doc:"Task identifier"`
}

type getTaskOutput struct {
	Body contract.Data[taskData]
}

type createTaskInput struct {
	Body taskCreateBody
}

type createTaskOutput struct {
	Body contract.Data[taskData]
}

func (h *Handler) list(ctx context.Context, input *listTasksInput) (*listTasksOutput, error) {
	page, perPage := contract.ClampPage(input.Page, input.PerPage)
	q := h.DB.WithContext(ctx).Model(&Task{})
	var total int64
	if err := q.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list tasks"))
	}
	var rows []Task
	if err := q.Order("id").Offset(contract.PageOffset(page, perPage)).Limit(perPage).Find(&rows).Error; err != nil {
		return nil, contract.WithContext(ctx, contract.Internal("list tasks"))
	}
	items := make([]taskData, 0, len(rows))
	for _, row := range rows {
		items = append(items, toTaskData(row))
	}
	return &listTasksOutput{
		Body: contract.DataMeta[[]taskData, contract.PageMeta]{
			Data: items,
			Meta: &contract.PageMeta{Page: page, PerPage: perPage, Total: total},
		},
	}, nil
}

func (h *Handler) get(ctx context.Context, input *getTaskInput) (*getTaskOutput, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, contract.WithContext(ctx, contract.NotFound("task not found"))
	}
	var row Task
	if err := h.DB.WithContext(ctx).First(&row, uint(id)).Error; err != nil {
		return nil, database.MapLoadError(ctx, err, "task not found", "load task")
	}
	return &getTaskOutput{Body: contract.Data[taskData]{Data: toTaskData(row)}}, nil
}

func (h *Handler) create(ctx context.Context, input *createTaskInput) (*createTaskOutput, error) {
	if h.Hooks == nil {
		return nil, contract.WithContext(ctx, contract.Internal("create task: Handler.Hooks is not set"))
	}
	row := taskFromCreateBody(input.Body)
	if err := h.Hooks.BeforeCreate(ctx, &row, input.Body); err != nil {
		return nil, err
	}
	if err := h.DB.WithContext(ctx).Create(&row).Error; err != nil {
		return nil, database.MapPersistError(ctx, err, "resource already exists", "create task")
	}
	return &createTaskOutput{Body: contract.Data[taskData]{Data: toTaskData(row)}}, nil
}

// Register mounts task Huma routes, wiring the human-owned Hooks.
func Register(app *framework.App) {
	h := &Handler{DB: app.DB(), Hooks: Hooks{}}
	prefix := app.Config().API.Prefix
	api := app.API()

	huma.Register(api, huma.Operation{
		OperationID: "list-tasks",
		Method:      http.MethodGet,
		Path:        prefix + "/tasks",
		Summary:     "List tasks",
		Tags:        []string{"Tasks"},
	}, h.list)

	huma.Register(api, huma.Operation{
		OperationID: "get-task",
		Method:      http.MethodGet,
		Path:        prefix + "/tasks/{id}",
		Summary:     "Get a task",
		Tags:        []string{"Tasks"},
	}, h.get)

	huma.Register(api, huma.Operation{
		OperationID: "create-task",
		Method:      http.MethodPost,
		Path:        prefix + "/tasks",
		Summary:     "Create a task",
		Tags:        []string{"Tasks"},
	}, h.create)

}
