package resourcegen

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	// GeneratedBanner marks files written by this generator. User-owned files
	// without the banner are refused unless --force is set. Identical re-runs
	// rewrite the same bytes (idempotent).
	GeneratedBanner = "Code generated by gombit make resource. DO NOT EDIT."

	defaultAPIPrefix = "/api/v1"
	defaultUI        = "minimal"
	serverMainRel    = "cmd/server/main.go"
	platformDBRel    = "internal/platform/database.go"
	resourcesTSRel   = "frontend/src/resources.tsx"
)

// Options configures resource generation inside an existing application.
type Options struct {
	WorkDir string
	Name    string
	Fields  []string
	// ID is the primary key strategy: uint (default, gorm.Model) or uuid.
	ID       string
	Service  bool
	Repo     bool
	DryRun   bool
	Force    bool
	Stdout   io.Writer
	Stderr   io.Writer
	AtlasBin string
	// SkipMigrations is the explicit opt-in to scaffolding the resource and
	// persisting the loader/registry state without generating the Atlas SQL diff.
	// It makes the committed output independent of whether Atlas is installed, at
	// the cost of a registry-ahead-of-SQL state the developer knowingly accepts
	// (#300).
	SkipMigrations bool

	skipAtlas bool
}

func (opts *Options) normalize() error {
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}
	if opts.Stderr == nil {
		opts.Stderr = io.Discard
	}
	if opts.WorkDir == "" {
		opts.WorkDir = "."
	}
	workDir, err := filepath.Abs(opts.WorkDir)
	if err != nil {
		return fmt.Errorf("resourcegen: resolve work dir: %w", err)
	}
	opts.WorkDir = workDir
	if opts.AtlasBin == "" {
		opts.AtlasBin = "atlas"
	}
	return nil
}

// ensureAtlas fails closed when this run would generate migration SQL but the
// Atlas binary (opts.AtlasBin) cannot be resolved. A dry run writes nothing and
// SkipMigrations is the explicit opt-out, so neither needs Atlas. This is the
// single place make resource resolves Atlas; there is no silent fallback that
// scaffolds without migrations (#300).
func (opts Options) ensureAtlas() error {
	if opts.DryRun || opts.SkipMigrations || opts.skipAtlas {
		return nil
	}
	if path, err := lookPath(opts.AtlasBin); err == nil && path != "" {
		return nil
	}
	rerun := append([]string{opts.Name}, opts.Fields...)
	for _, flag := range []struct {
		set  bool
		name string
	}{{opts.Service, "--service"}, {opts.Repo, "--repo"}, {opts.Force, "--force"}} {
		if flag.set {
			rerun = append(rerun, flag.name)
		}
	}
	if id := strings.TrimSpace(opts.ID); id != "" && !strings.EqualFold(id, "uint") && !strings.EqualFold(id, "integer") {
		rerun = append(rerun, "--id", id)
	}
	return fmt.Errorf(
		"resourcegen: Atlas is required to generate database migrations (%q not found on PATH).\n\n"+
			"Install Atlas and retry, or run:\n\n"+
			"    gombit make resource %s --skip-migrations\n\n"+
			"to create the resource without generating migration SQL",
		opts.AtlasBin, strings.Join(rerun, " "))
}

func (opts Options) validateAppLayout() error {
	for _, rel := range []string{"go.mod", serverMainRel, platformDBRel} {
		path := filepath.Join(opts.WorkDir, filepath.FromSlash(rel))
		if _, err := os.Stat(path); err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return fmt.Errorf("resourcegen: %s not found; run this command from a gombit new application directory", rel)
			}
			return fmt.Errorf("resourcegen: stat %s: %w", rel, err)
		}
	}
	return nil
}
