package resourcegen

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

const (
	// GeneratedBanner marks files written by this generator. User-owned files
	// without the banner are refused unless --force is set. Identical re-runs
	// rewrite the same bytes (idempotent).
	GeneratedBanner = "Code generated by gombit make resource. DO NOT EDIT."

	defaultAPIPrefix = "/api/v1"
	defaultUI        = "minimal"
	serverMainRel    = "cmd/server/main.go"
	platformDBRel    = "internal/platform/database.go"
	resourcesTSRel   = "frontend/src/resources.tsx"
)

// Options configures resource generation inside an existing application.
type Options struct {
	WorkDir  string
	Name     string
	Fields   []string
	Service  bool
	Repo     bool
	DryRun   bool
	Force    bool
	Stdout   io.Writer
	Stderr   io.Writer
	AtlasBin string
	// SkipMigrations is the explicit opt-in to scaffolding the resource and
	// persisting the loader/registry state without generating the Atlas SQL diff.
	// It makes the committed output independent of whether Atlas is installed, at
	// the cost of a registry-ahead-of-SQL state the developer knowingly accepts
	// (#300).
	SkipMigrations bool

	skipAtlas bool
}

func (opts *Options) normalize() error {
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}
	if opts.Stderr == nil {
		opts.Stderr = io.Discard
	}
	if opts.WorkDir == "" {
		opts.WorkDir = "."
	}
	workDir, err := filepath.Abs(opts.WorkDir)
	if err != nil {
		return fmt.Errorf("resourcegen: resolve work dir: %w", err)
	}
	opts.WorkDir = workDir
	if opts.AtlasBin == "" {
		opts.AtlasBin = "atlas"
	}
	return nil
}

func (opts Options) validateAppLayout() error {
	for _, rel := range []string{"go.mod", serverMainRel, platformDBRel} {
		path := filepath.Join(opts.WorkDir, filepath.FromSlash(rel))
		if _, err := os.Stat(path); err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return fmt.Errorf("resourcegen: %s not found; run this command from a gombit new application directory", rel)
			}
			return fmt.Errorf("resourcegen: stat %s: %w", rel, err)
		}
	}
	return nil
}
